version: '3.8'
services:
  db:
    image: postgres:15
    container_name: c-postgres
    restart: always
    ports:
      - "3332:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapassW
      POSTGRES_DB: inflearn_clone
    volumes:
      - inflearn_clone_db:/var/lib/postgresql/data

volumes:
  inflearn_clone_db:
